export const BOOK_CONDITIONS = ['LIKE_NEW', 'GOOD', 'FAIR', 'POOR'];
export const BOOK_STATUSES = ['AVAILABLE', 'UNAVAILABLE', 'EXCHANGED'];
export const EXCHANGE_STATUSES = ['PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'];
